// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_b1-H4Z3bx1NKdRvICGTpr7IOf2IWTCM',
    appId: '1:426539705078:web:38d7a4fc3e3c2ae24942d7',
    messagingSenderId: '426539705078',
    projectId: 'lost-and-found-d7a43',
    authDomain: 'lost-and-found-d7a43.firebaseapp.com',
    storageBucket: 'lost-and-found-d7a43.firebasestorage.app',
    measurementId: 'G-W2QK9WQNBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIl_ESXhBE75K74tKVzJVqss2XUTX-2G4',
    appId: '1:426539705078:android:2dc3f3fbecbdedf04942d7',
    messagingSenderId: '426539705078',
    projectId: 'lost-and-found-d7a43',
    storageBucket: 'lost-and-found-d7a43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBykl9cJvFO0JwY2qfEpWJHbSeIX5a3yjk',
    appId: '1:426539705078:ios:e0c981bf2132aac34942d7',
    messagingSenderId: '426539705078',
    projectId: 'lost-and-found-d7a43',
    storageBucket: 'lost-and-found-d7a43.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundFront',
  );
}
